[package]
name = "ran"
version = "0.1.1"
edition = "2021"
authors = ["Libor Spacek"]
description = """Simple, fast random numbers generation"""
readme = "README.md"
homepage = "https://github.com/liborty/random"
repository = "https://github.com/liborty/random"
license-file = "LICENSE"
keywords = ["merge-sort","set-operations","ranking-searching","random","generic-vectors"]
categories = ["mathematics","algorithms","data-structures","rust-patterns","simulation"]
include = [
    "src/*.rs",
    "tests/*.rs",
    "Cargo.toml",
    "README.md",
    "LICENSE"
]
[badges]
maintenance = { status = "actively-developed" }
[lib]
[dependencies]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
